# Generated by Django 4.2.5 on 2023-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
