# Generated by Django 4.2.5 on 2023-09-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_transactions_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='user_name',
            new_name='user',
        ),
    ]
