# Generated by Django 4.1 on 2023-10-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_user_name_transactions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='price',
        ),
    ]
